# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias l='ls -AlFh'
#alias ls='ls -A --color'
alias lt='ls -Flt'
alias la='ls -FShl'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# added by Anaconda3 4.2.0 installer
export PATH="/home/funnybomb/anaconda3/bin:$PATH"
###
export PATH="~/wangyubin:~/bin:$PATH"
export PS1="\[\e[36;1m\][\A@\h \W]\$\[\e[0m\]"
export HISTTIMEFORMAT="%d/%m/%y %T "
#alias sfm='rsync -avP --max-size='2G' --exclude=traj_data moon:~/analysis/ /Users/funnybomb/百度云同步盘/MD/analysis/'
#alias sfmx='rsync -avP --exclude=*dcd --exclude=data --exclude=traj_data moon:~/analysis/ /Users/funnybomb/百度云同步盘/MD/analysis/'
#alias sfe='rsync -avP --exclude=data --exclude=traj_data eros:~/analysis/ /Users/funnybomb/百度云同步盘/MD/analysis/'
#alias sfex='rsync -avP --exclude=*dcd --exclude=data --exclude=traj_data eros:~/analysis/ /Users/funnybomb/百度云同步盘/MD/analysis/'
#alias stpcub='rsync -avP /Users/funnybomb/百度云同步盘/MD/ pcub:~/md/'
#alias stm='rsync -avP /Users/funnybomb/百度云同步盘/MD/analysis/ moon:~/analysis/'
alias d='cd ~/MD/reanalysis/'
alias rm='rm -if'
alias les='less -S'
alias dfh='df -h'
alias s='cd ..'
#alias sed='gsed'
alias f="for i in '2aef' 'fg' '3rbz' '2fy8';do"
alias duh='du -d 1 -h'
alias dum='du -d 1 -m'
alias dug='du -d 1 -g'
alias rmr='rm -r'
alias les='less -S '
alias qu='qstat -u wangyu'
alias q='qstat'
alias x_echo='xargs -i echo less -S {}|sh'
alias bc='bc -lq'
alias tlog='2>/tmp/log'
alias colt='column -t|less -S'
alias b='cd -'
alias scr='screen -re^tt'
alias scs='screen -Se^tt'
alias scl='screen -lse^tt'
alias sck='screenkill.sh'
alias scd='screen -D -RR'
#alias ls='/bin/ls -F --color=tty --show-control-chars'
alias sedi='sed -i 's/\s\+/\t/''
alias addlast='history | tail -n2 | head -n1  | cut -d" " -f7- >> ~/process.sh '
alias update='source ~/.bashrc'
alias pc='proxychains'
alias sap='source activate py27'
alias sdp='source deactivate py27'

### for git
alias ga='git add -A'
alias gc='git diff --cached'
alias gst='git status'
alias gm='git commit -m'
alias gl='git hist'
alias gps='git push origin master'

# added by Anaconda3 4.2.0 installer
export PATH="/home/fcy/anaconda3/bin:$PATH"
export PATH="$PATH:/home/fcy/SeqMule/bin"
export PATH="$PATH:/home/fcy/SeqMule/exe"
#export PATH="$PATH:/home/fcy/SeqMule/exe/bwa"
#export PATH="$PATH:/home/fcy/SeqMule/exe/samtools"

# for ngs analysis
alias gatk='java -jar /home/fcy/bin/GenomeAnalysisTK.jar'
alias picard='java -jar /home/fcy/bin/picard.jar'
